config/routes.rb
Rails.application.routes.draw do
  resources :user_books
  resources :users

  root 'user_books#index'

  resources :books do
    member do
      get :delete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :user_books
    has_many :users, through: :user_books

  validates :title, :author, :price, :published_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_books
    has_many :books, through: :user_books
end

app/models/user_book.rb
class UserBook < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to root_path
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully deleted."
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :price, :published_date)
  end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :set_user_book, only: %i[ show edit update destroy ]

  # GET /user_books or /user_books.json
  def index
    @user_books = UserBook.all
  end

  # GET /user_books/1 or /user_books/1.json
  def show
  end

  # GET /user_books/new
  def new
    @user_book = UserBook.new
  end

  # GET /user_books/1/edit
  def edit
  end

  # POST /user_books or /user_books.json
  def create
    @user_book = UserBook.new(user_book_params)

    respond_to do |format|
      if @user_book.save
        format.html { redirect_to @user_book, notice: "User book was successfully created." }
        format.json { render :show, status: :created, location: @user_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_books/1 or /user_books/1.json
  def update
    respond_to do |format|
      if @user_book.update(user_book_params)
        format.html { redirect_to @user_book, notice: "User book was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_books/1 or /user_books/1.json
  def destroy
    @user_book.destroy!

    respond_to do |format|
      format.html { redirect_to user_books_path, notice: "User book was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_book
      @user_book = UserBook.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_book_params
      params.expect(user_book: [ :user_id, :book_id ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :username ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= form_with model: @book do |form| %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div>
    <%= form.label :published_date %>
    <%= form.date_select :published_date %>
  </div>

  <%= form.submit %>

<% end %>

app/views/books/index.html.erb
<h1>Book Collection</h1>

<p style="color: green"><%= flash[:notice] %></p>

<%= link_to "Add New Book", new_book_path %>
<h2>This is a test version </h2>

<ul>
  <% @books.each do |book| %>
    <li>
      <%= book.title %> |
      <%= link_to "Show", book_path(book) %> |
      <%= link_to "Edit", edit_book_path(book) %> |
      <%= link_to "Delete", book_path(book), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<%= form_with model: @book do |form| %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div>
    <%= form.label :published_date %>
    <%= form.date_select :published_date %>
  </div>

  <%= form.submit %>

<% end %>

app/views/books/show.html.erb
<h1>Book Details</h1>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<%= link_to "Back to Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <p><%= message %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/user_books/_form.html.erb
<%= form_with(model: user_book) do |form| %>
  <% if user_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_book.errors.count, "error") %> prohibited this user_book from being saved:</h2>

      <ul>
        <% user_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <%= form.label :user_id, style: "display: block" %>
  <%= form.select :user_id,
      User.order(:username).map { |user| [user.username, user.id] },
      include_blank: true,
      id: "id_of_the_user_id_select_box" %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.select :book_id,
        Book.order(:title).map { |book| [book.title, book.id] },
        include_blank: true,
        id: "id_of_the_book_id_select_box" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_books/_user_book.html.erb
<div id="<%= dom_id user_book %>">
  <p>
    <strong>User:</strong>
    <%= user_book.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= user_book.book_id %>
  </p>

</div>

app/views/user_books/edit.html.erb
<% content_for :title, "Editing user book" %>

<h1>Editing user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Show this user book", @user_book %> |
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Books</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Book Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_books.each do |user_book| %>
      <tr>
        <td><%= user_book.user.username %></td>
        <td><%= user_book.book.title %></td>
        <td><%= link_to 'Show', user_book %></td>
        <td><%= link_to 'Edit', edit_user_book_path(user_book) %></td>
        <td><%= link_to 'Destroy', user_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<%= link_to 'New User Book', new_user_book_path %>
<br>
<%= link_to 'Book index', books_path %>
<br>
<%= link_to 'User index', users_path %>

app/views/user_books/new.html.erb
<% content_for :title, "New user book" %>

<h1>New user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_book %>

<div>
  <%= link_to "Edit this user book", edit_user_book_path(@user_book) %> |
  <%= link_to "Back to user books", user_books_path %>

  <%= button_to "Destroy this user book", @user_book, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>